[project]
name = 'executor DAO'
description = ''
authors = []
telemetry = false
cache_dir = '.cache'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'

[contracts.proposal-trait]
path = "contracts/traits/proposal-trait.clar"
clarity_version = 2
epoch = 2.3

[contracts.extension-trait]
path = "contracts/traits/extension-trait.clar"
clarity_version = 2
epoch = 2.3

[contracts.executor-dao]
path = "contracts/executor-dao.clar"
depends_on = ["proposal-trait", "extension-trait"]
clarity_version = 2
epoch = 2.3

[contracts.ede004-emergency-execute]
path = "contracts/extensions/ede004-emergency-execute.clar"
depends_on = ["executor-dao", "extension-trait", "ede001-proposal-voting"]
clarity_version = 2
epoch = 2.3

[contracts.ede006-treasury]
path = "contracts/extensions/ede006-treasury.clar"
depends_on = ["executor-dao", "extension-trait"]
clarity_version = 2
epoch = 2.3

[contracts.ede007-snapshot-proposal-voting-v5]
path = "contracts/extensions/ede007-snapshot-proposal-voting-v5.clar"
depends_on = ["executor-dao", "extension-trait"]
clarity_version = 2
epoch = 2.3

[contracts.ede008-flexible-funded-proposal-submission]
path = "contracts/extensions/ede008-flexible-funded-proposal-submission.clar"
depends_on = ["executor-dao", "extension-trait"]
clarity_version = 2
epoch = 2.3

[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = true
trusted_caller = true
callee_filter = true
